'use client';

import { useState, useEffect } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { motion } from 'framer-motion';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog';
import { 
  Key,
  Users,
  UserPlus,
  Copy,
  CheckCircle,
  Plus,
  Settings,
  Trash2,
  AlertTriangle
} from 'lucide-react';
import { toast } from 'sonner';
import { collection, query, where, getDocs, doc, setDoc, serverTimestamp, deleteDoc } from 'firebase/firestore';
import { db } from '@/lib/firebase';

interface AccessCode {
  id: string;
  communityId: string;
  isUsed: boolean;
  usedBy?: string;
  usedAt?: any;
  createdAt: any;
  type: string;
  description?: string;
}

interface User {
  id: string;
  name: string;
  email: string;
  role: string;
  communityId: string;
  createdAt: any;
  lastLogin: any;
}

export default function ManageUsers() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const [accessCodes, setAccessCodes] = useState<AccessCode[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [loading, setLoading] = useState(true);

  // Check admin access
  useEffect(() => {
    if (status === 'loading') return;
    
    if (!session?.user?.email || session.user.role !== 'admin') {
      router.push('/dashboard');
      return;
    }
    
    fetchUsersAndAccessCodes();
  }, [session, status, router]);

  const fetchUsersAndAccessCodes = async () => {
    try {
      if (!session?.user?.communityId) return;
      
      // Fetch access codes
      const accessCodesQuery = query(
        collection(db, 'accessCodes'),
        where('communityId', '==', session.user.communityId)
      );
      
      const accessCodesSnapshot = await getDocs(accessCodesQuery);
      const accessCodesData = accessCodesSnapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      } as AccessCode));
      
      setAccessCodes(accessCodesData);
      
      // Fetch users
      const usersQuery = query(
        collection(db, 'users'),
        where('communityId', '==', session.user.communityId)
      );
      
      const usersSnapshot = await getDocs(usersQuery);
      const usersData = usersSnapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      } as User));
      
      setUsers(usersData);
    } catch (error) {
      console.error('Error fetching users and access codes:', error);
      toast.error('Failed to load user data');
    } finally {
      setLoading(false);
    }
  };

  const generateAccessCode = async () => {
    try {
      if (!session?.user?.communityId) return;
      
      // Generate random access code
      const code = Math.random().toString(36).substr(2, 8).toUpperCase();
      
      await setDoc(doc(db, 'accessCodes', code), {
        communityId: session.user.communityId,
        isUsed: false,
        createdAt: serverTimestamp(),
        type: 'resident',
        description: `Generated by ${session.user.name || session.user.email}`
      });
      
      toast.success(`Access code ${code} generated successfully!`);
      fetchUsersAndAccessCodes();
    } catch (error) {
      console.error('Error generating access code:', error);
      toast.error('Failed to generate access code');
    }
  };

  const deleteAccessCode = async (codeId: string) => {
    try {
      const codeRef = doc(db, 'accessCodes', codeId);
      await deleteDoc(codeRef);
      toast.success('Access code deleted successfully!');
      fetchUsersAndAccessCodes();
    } catch (error) {
      console.error('Error deleting access code:', error);
      toast.error('Failed to delete access code');
    }
  };

  const deleteUser = async (userId: string, userEmail: string) => {
    try {
      const userRef = doc(db, 'users', userId);
      await deleteDoc(userRef);
      toast.success(`User ${userEmail} deleted successfully!`);
      fetchUsersAndAccessCodes();
    } catch (error) {
      console.error('Error deleting user:', error);
      toast.error('Failed to delete user');
    }
  };

  const autoReplaceUsedCode = async (usedCodeId: string) => {
    try {
      const response = await fetch('/api/access-codes/auto-replace', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ usedCodeId }),
      });

      const data = await response.json();

      if (response.ok) {
        toast.success(`Used code deleted and new code ${data.newCode} generated!`);
        fetchUsersAndAccessCodes();
      } else {
        toast.error(data.error || 'Failed to replace access code');
      }
    } catch (error) {
      console.error('Error auto-replacing access code:', error);
      toast.error('Failed to replace access code');
    }
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast.success('Copied to clipboard!');
  };

  if (status === 'loading' || loading) {
    return (
      <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-2xl flex items-center justify-center mx-auto mb-4 animate-pulse">
            <Users className="w-8 h-8 text-white" />
          </div>
          <p className="text-slate-800 dark:text-slate-400">Loading user management...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 p-4">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-4xl font-bold bg-gradient-to-r from-indigo-500 to-purple-600 bg-clip-text text-transparent mb-2">
                Manage Users
              </h1>
              <p className="text-slate-800 dark:text-slate-400 text-lg">
                Handle access codes and community member registration
              </p>
            </div>
          </div>
        </motion.div>

        {/* Stats Cards */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8"
        >
          <Card>
            <CardContent className="p-6">
              <div className="flex items-center">
                <Key className="w-8 h-8 text-blue-500 mr-3" />
                <div>
                  <p className="text-sm font-medium text-slate-800 dark:text-slate-400">Total Access Codes</p>
                  <p className="text-2xl font-bold">{accessCodes.length}</p>
                </div>
              </div>
            </CardContent>
          </Card>
          
          <Card>
            <CardContent className="p-6">
              <div className="flex items-center">
                <CheckCircle className="w-8 h-8 text-green-500 mr-3" />
                <div>
                  <p className="text-sm font-medium text-slate-800 dark:text-slate-400">Used Codes</p>
                  <p className="text-2xl font-bold">{accessCodes.filter(code => code.isUsed).length}</p>
                </div>
              </div>
            </CardContent>
          </Card>
          
          <Card>
            <CardContent className="p-6">
              <div className="flex items-center">
                <Users className="w-8 h-8 text-purple-500 mr-3" />
                <div>
                  <p className="text-sm font-medium text-slate-800 dark:text-slate-400">Total Users</p>
                  <p className="text-2xl font-bold">{users.length}</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Generate New Access Code */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="mb-8"
        >
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center">
                <UserPlus className="w-5 h-5 mr-2" />
                Generate Access Code
              </CardTitle>
              <CardDescription>
                Create a new access code for residents to join the community
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Button onClick={generateAccessCode} className="bg-gradient-to-r from-indigo-500 to-purple-600">
                <Plus className="w-4 h-4 mr-2" />
                Generate New Code
              </Button>
            </CardContent>
          </Card>
        </motion.div>

        {/* Access Codes List */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="mb-8"
        >
          <Card>
            <CardHeader>
              <CardTitle>Access Codes</CardTitle>
              <CardDescription>
                Manage access codes for community registration
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {accessCodes.map((code) => (
                  <div
                    key={code.id}
                    className={`p-4 rounded-lg border-2 transition-all ${
                      code.isUsed
                        ? 'border-green-200 bg-green-50 dark:border-green-800 dark:bg-green-900/20'
                        : 'border-blue-200 bg-blue-50 dark:border-blue-800 dark:bg-blue-900/20'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-3">
                        <div className={`p-2 rounded-lg ${code.isUsed ? 'bg-green-100 dark:bg-green-800' : 'bg-blue-100 dark:bg-blue-800'}`}>
                          {code.isUsed ? (
                            <CheckCircle className="w-5 h-5 text-green-600 dark:text-green-400" />
                          ) : (
                            <Key className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                          )}
                        </div>
                        <div>
                          <p className="font-mono text-lg font-bold">{code.id}</p>
                          <p className="text-sm text-slate-800 dark:text-slate-400">
                            {code.isUsed ? `Used by: ${code.usedBy}` : 'Available for use'}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center space-x-2">
                        <Badge variant={code.isUsed ? "default" : "secondary"}>
                          {code.isUsed ? 'Used' : 'Available'}
                        </Badge>
                        {!code.isUsed && (
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => copyToClipboard(code.id)}
                          >
                            <Copy className="w-4 h-4" />
                          </Button>
                        )}
                        {code.isUsed ? (
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => autoReplaceUsedCode(code.id)}
                            className="text-amber-600 hover:text-amber-700 hover:bg-amber-50"
                          >
                            <Plus className="w-4 h-4 mr-1" />
                            Replace
                          </Button>
                        ) : null}
                        <AlertDialog>
                          <AlertDialogTrigger asChild>
                            <Button
                              size="sm"
                              variant="outline"
                              className="text-red-600 hover:text-red-700 hover:bg-red-50"
                            >
                              <Trash2 className="w-4 h-4" />
                            </Button>
                          </AlertDialogTrigger>
                          <AlertDialogContent>
                            <AlertDialogHeader>
                              <AlertDialogTitle>Delete Access Code</AlertDialogTitle>
                              <AlertDialogDescription>
                                Are you sure you want to delete access code <strong>{code.id}</strong>? 
                                {code.isUsed ? ' This code has already been used.' : ' This code is still available for use.'}
                                <br />
                                <span className="text-red-600">This action cannot be undone.</span>
                              </AlertDialogDescription>
                            </AlertDialogHeader>
                            <AlertDialogFooter>
                              <AlertDialogCancel>Cancel</AlertDialogCancel>
                              <AlertDialogAction 
                                onClick={() => deleteAccessCode(code.id)}
                                className="bg-red-600 hover:bg-red-700"
                              >
                                Delete Code
                              </AlertDialogAction>
                            </AlertDialogFooter>
                          </AlertDialogContent>
                        </AlertDialog>
                      </div>
                    </div>
                  </div>
                ))}
                
                {accessCodes.length === 0 && (
                  <div className="text-center py-8">
                    <Key className="w-16 h-16 text-slate-400 mx-auto mb-4" />
                    <h3 className="text-xl font-semibold mb-2">No Access Codes</h3>
                    <p className="text-slate-800 dark:text-slate-400 mb-4">
                      Generate your first access code to allow residents to join.
                    </p>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Users List */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
        >
          <Card>
            <CardHeader>
              <CardTitle>Community Users</CardTitle>
              <CardDescription>
                All registered users in your community
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {users.map((user) => (
                  <div
                    key={user.id}
                    className="p-4 rounded-lg border bg-white dark:bg-slate-800 hover:shadow-md transition-all"
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-3">
                        <div className="w-10 h-10 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-full flex items-center justify-center">
                          <span className="text-white font-bold">
                            {user.name?.charAt(0) || user.email.charAt(0).toUpperCase()}
                          </span>
                        </div>
                        <div>
                          <p className="font-semibold">{user.name || 'No name set'}</p>
                          <p className="text-sm text-slate-800 dark:text-slate-400">{user.email}</p>
                        </div>
                      </div>
                      <div className="flex items-center space-x-2">
                        <Badge variant={user.role === 'admin' ? 'default' : 'secondary'}>
                          {user.role}
                        </Badge>
                        <p className="text-sm text-slate-700">
                          Joined {user.createdAt?.toDate?.()?.toLocaleDateString() || 'Unknown'}
                        </p>
                        {user.role !== 'admin' && (
                          <AlertDialog>
                            <AlertDialogTrigger asChild>
                              <Button
                                size="sm"
                                variant="outline"
                                className="text-red-600 hover:text-red-700 hover:bg-red-50"
                              >
                                <Trash2 className="w-4 h-4" />
                              </Button>
                            </AlertDialogTrigger>
                            <AlertDialogContent>
                              <AlertDialogHeader>
                                <AlertDialogTitle>Delete User</AlertDialogTitle>
                                <AlertDialogDescription>
                                  Are you sure you want to delete user <strong>{user.name || user.email}</strong>? 
                                  <br />
                                  Email: <strong>{user.email}</strong>
                                  <br />
                                  <span className="text-red-600">This will permanently remove all user data and cannot be undone.</span>
                                </AlertDialogDescription>
                              </AlertDialogHeader>
                              <AlertDialogFooter>
                                <AlertDialogCancel>Cancel</AlertDialogCancel>
                                <AlertDialogAction 
                                  onClick={() => deleteUser(user.id, user.email)}
                                  className="bg-red-600 hover:bg-red-700"
                                >
                                  Delete User
                                </AlertDialogAction>
                              </AlertDialogFooter>
                            </AlertDialogContent>
                          </AlertDialog>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
                
                {users.length === 0 && (
                  <div className="text-center py-8">
                    <Users className="w-16 h-16 text-slate-400 mx-auto mb-4" />
                    <h3 className="text-xl font-semibold mb-2">No Users Yet</h3>
                    <p className="text-slate-800 dark:text-slate-400">
                      Users will appear here once they register with access codes.
                    </p>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
}